# Generated by Django 4.1.2 on 2022-10-26 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BrandApp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("link", models.CharField(max_length=2056)),
                ("online", models.BooleanField()),
                ("offline", models.BooleanField()),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
