# Generated by Django 4.1.2 on 2022-10-26 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="brandapp", name="offline",),
        migrations.AlterField(
            model_name="brandapp",
            name="online",
            field=models.BooleanField(default=False),
        ),
    ]
