# Generated by Django 4.1.2 on 2022-10-26 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_brandapp_offline_alter_brandapp_online"),
    ]

    operations = [
        migrations.CreateModel(
            name="MostUsedApp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("appname", models.CharField(max_length=200)),
                ("url", models.CharField(max_length=2056)),
                ("parent_company", models.CharField(max_length=200)),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["parent_company"],},
        ),
        migrations.AlterModelOptions(
            name="brandapp", options={"ordering": ["-online", "date"]},
        ),
    ]
