# Generated by Django 4.1.2 on 2022-10-27 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_realtimedata_alter_brandapp_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="realtimedata", options={"ordering": ["appname"]},
        ),
    ]
