# Generated by Django 4.1.2 on 2022-10-27 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_realtimedata_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="realtimedata",
            name="online",
            field=models.BooleanField(default=False),
        ),
    ]
