# Generated by Django 4.1.2 on 2022-10-27 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_realtimedata_online"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="realtimedata", options={"ordering": ["-online", "appname"]},
        ),
        migrations.AlterField(
            model_name="brandapp", name="online", field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name="realtimedata",
            name="online",
            field=models.CharField(max_length=25),
        ),
    ]
