# Generated by Django 4.1.2 on 2022-10-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_realtimedata_options_alter_brandapp_online_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brandapp",
            name="online",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="realtimedata",
            name="online",
            field=models.BooleanField(default=False),
        ),
    ]
