# Generated by Django 4.1.2 on 2022-10-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_alter_brandapp_online_alter_realtimedata_online"),
    ]

    operations = [
        migrations.CreateModel(
            name="RealTimeBigData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("appname", models.CharField(max_length=200)),
                ("url", models.CharField(max_length=2056)),
                ("online", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["-online", "-created"],},
        ),
        migrations.RenameModel(old_name="RealTimeData", new_name="LiveData",),
        migrations.DeleteModel(name="BrandApp",),
    ]
