# Generated by Django 4.1.2 on 2022-11-01 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_realtimebigdata_rename_realtimedata_livedata_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="livedata",
            name="color",
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name="livedata",
            name="logo",
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
