# Generated by Django 4.1.2 on 2022-11-19 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_alter_livedata_options_alter_realtimebigdata_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Visitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip", models.CharField(max_length=45)),
                ("device_type", models.CharField(max_length=10, null=True)),
                (
                    "device_name",
                    models.CharField(blank=True, max_length=125, null=True),
                ),
                ("device_OS", models.CharField(blank=True, max_length=125, null=True)),
                ("browser", models.CharField(blank=True, max_length=125, null=True)),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
